# Generated by Django 6.0.3 on 2026-04-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='reaccess_token',
            new_name='access_token',
        ),
    ]
